"use client";

import { useEffect, useState, useTransition } from "react";
import { createDraft, updateDraft } from "@/app/(app)/outreach/actions";

/** Editable draft grounded in evidence + the sender's configured capabilities.
 * Copy/mailto only — never marks anything as sent (spec §6). */
export function DraftPanel({
  personId,
  draftId,
  onDraftId,
}: {
  personId: string;
  draftId: string | null;
  onDraftId: (id: string) => void;
}) {
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [pending, start] = useTransition();
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (draftId) return; // already generated by the caller
    start(async () => {
      const res = await createDraft(personId);
      if (res.ok) onDraftId(res.draftId);
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [personId]);

  if (pending && !draftId) {
    return (
      <div className="rounded-[10px] border p-3 text-[12px] text-[var(--muted)]" style={{ borderColor: "var(--card-border)" }}>
        Drafting…
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2 rounded-[10px] border p-3" style={{ borderColor: "var(--card-border)", background: "rgba(150,185,255,.03)" }}>
      <input
        value={subject}
        onChange={(e) => setSubject(e.target.value)}
        placeholder="Subject"
        className="w-full rounded-[8px] border bg-transparent px-2.5 py-1.5 text-[12.5px] text-[var(--fg)] outline-none"
        style={{ borderColor: "var(--card-border)" }}
      />
      <textarea
        value={body}
        onChange={(e) => setBody(e.target.value)}
        rows={6}
        placeholder="Draft body…"
        className="w-full resize-none rounded-[8px] border bg-transparent px-2.5 py-1.5 text-[12.5px] leading-relaxed text-[var(--fg)] outline-none"
        style={{ borderColor: "var(--card-border)" }}
      />
      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          disabled={!draftId || pending}
          onClick={() => draftId && start(async () => { await updateDraft(draftId, subject, body); })}
          className="rounded-[8px] px-3 py-1.5 text-[12px] font-semibold disabled:opacity-60"
          style={{ background: "var(--accent-btn)", color: "var(--accent-btn-ink)" }}
        >
          Save edits
        </button>
        <button
          type="button"
          onClick={() => {
            navigator.clipboard?.writeText(`${subject}\n\n${body}`);
            setSaved(true);
            setTimeout(() => setSaved(false), 1500);
          }}
          className="rounded-[8px] border px-3 py-1.5 text-[12px] text-[var(--muted)]"
          style={{ borderColor: "var(--card-border)" }}
        >
          {saved ? "Copied" : "Copy"}
        </button>
      </div>
      <p className="text-[10.5px] text-[var(--faint)]">
        This is a draft only. Copying or opening your email app does not log outreach — use “Log outreach” once you&rsquo;ve actually sent it.
      </p>
    </div>
  );
}
